spring.application.name=AeroportSpring

# --- Base H2 ---
spring.datasource.url=jdbc:h2:mem:aeroportdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- Console web H2 ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- OpenAPI / springdoc ---
# Document JSON : http://localhost:8080/v3/api-docs
# UI Scalar     : http://localhost:8080/docs
springdoc.api-docs.path=/v3/api-docs
springdoc.show-actuator=false
springdoc.writer-with-order-by-keys=true